#ifndef MAIN_H
#define MAIN_H

void *_calloc(unsigned int nmemb, unsigned int size);
char *string_nconcat(char *s1, char *s2, unsigned int n);
void *malloc_checked(unsigned int b);
char *_memcpy(char *dest, char *src, unsigned int n);
char *_memset(char *s, char b, int n);
char *_strcat(char *dest, char *src);
char *_strchr(char *s, char c);
char *_strcpy(char *dest, char *src);
char *_strdup(char *str);
char *_strncat(char *dest, char *src, int n);
char *_strncpy(char *dest, char *src, int n);
char *_strstr(char *haystack, char *needle);
char *cap_string(char *str);
char *create_array(unsigned int size, char c);
char *leet(char *str);
char *rot13(char *str);
char *str_concat(char *s1, char *s2);
char *string_toupper(char *str);
int **alloc_grid(int width, int height);
int _abs(int n);
int _atoi(char *s);
int _isalpha(int c);
int _isdigit(int c);
int _islower(int c);
int _isupper(int c);
int _pow_recursion(int x, int y);
int _putchar(char c);
int _sqrt_recursion(int n);
int _strcmp(char *s1, char *s2);
int _strlen(char *s);
int _strlen_recursion(char *s);
int add(int num1, int num2);
int factorial(int n);
int is_prime_number(int n);
int mul(int a, int b);
int print_last_digit(int n);
int print_sign(int n);
unsigned int _strspn(char *s, char *accept);
void _print_rev_recursion(char *s);
void _puts(char *c);
void _puts_recursion(char *s);
void free_grid(int **grid, int height);
void jack_bauer(void);
void more_numbers(void);
void print_alphabet_x10(void);
void print_array(int *a, int n);
void print_buffer(char *b, int size);
void print_chessboard(char (*a)[8]);
void print_diagonal(int n);
void print_diagsums(int *a, int size);
void print_line(int n);
void print_most_numbers(void);
void print_number(int n);
void print_numbers(void);
void print_rev(char *s);
void print_square(int size);
void print_to_98(int n);
void print_triangle(int size);
void puts2(char *str);
void puts_half(char *str);
void reset_to_98(int *n);
void rev_string(char *s);
void reverse_array(int *a, int n);
void set_string(char **s, char *to);
void swap_int(int *a, int *b);
#endif
